# Use the README file as a reference to customize settings.

User:
  fields:
    default: email, encrypted_password, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, name, photo_file_name, photo_file_size, mobile_number, gender, authentication_token
    form: email, encrypted_password, reset_password_token, reset_password_sent_at, sign_in_count, current_sign_in_at, last_sign_in_at, current_sign_in_ip, last_sign_in_ip, name, photo_file_name, photo_file_size, mobile_number, gender, authentication_token
  relationships: posts, comments, devices
  application: Application
